/**
 * First version of this
 * code was generated by v0 by Vercel.
 * @see https://v0.dev/t/qcxQUXSj0L0
 */
import {Input} from '@/components/ui/input'
import {Button} from '@/components/ui/button'
import {Pill} from './ui/Pill'

export function NaughtyOrNiceTracker() {
	const kids = [
		{name: 'Emma', tally: 32},
		{name: 'Ethan', tally: 14},
		{name: 'Isabella', tally: 70},
		{name: 'Jayden', tally: -16},
		{name: 'Isabella', tally: -59},
		{name: 'Noah', tally: 19},
		{name: 'Mia', tally: -37},
		{name: 'Will', tally: -20},
		{name: 'Sam', tally: -91},
		{name: 'Brittney', tally: -98},
	]
	return (
		<section className="flex flex-col items-center">
			<div className="flex w-full flex-col">
				<div className="mb-4 flex space-x-2">
					<label className="grid grow items-center gap-2 md:grid-cols-3">
						<span>Search by name:</span>
						<Input
							className="md:col-span-2"
							placeholder="Search Child's Name"
						/>
					</label>
				</div>
				<div className="mb-2 flex items-center gap-2">
					Filters:
					<Button className="rounded-full border border-gray-300 px-3 py-1 text-sm">
						All
					</Button>
					<Button className="rounded-full border border-gray-300 px-3 py-1 text-sm">
						Naughty
					</Button>
					<Button className="rounded-full border border-gray-300 px-3 py-1 text-sm">
						Nice
					</Button>
				</div>
				<ul className="flex flex-col gap-1">
					{kids.map(({name, tally}) => (
						<li key={name} className="flex items-center justify-between">
							<div>
								<strong>{name}</strong>: <span>{tally} good deeds</span>
							</div>
							<span></span>
							{tally >= 0 ? (
								<Pill className="bg-primary-600">Nice 👼</Pill>
							) : (
								<Pill className="bg-secondary-600">Naughty 😈</Pill>
							)}
						</li>
					))}
				</ul>
			</div>
		</section>
	)
}
